### ISSUE TITLE
Unknown plugin "transform-runtime"

### ISSUE THREAD

**Issue by kosiakMD** [javisperez/vue-visible#2] opened 2017-05-30 08:45 UTC
Hello, in npm description "Dependencies" is "None", but have the next problem:

`...` - my specific path

    ERROR in /Users/.../dashboard.trademax-dev.se/~/vue-visible/dist/v-visible.js

    Module build failed: ReferenceError: Unknown plugin "transform-runtime" specified in 
    "/Users/.../node_modules/vue-visible/.babelrc" 

    at 0, attempted to resolve relative to     "/Users/.../node_modules/vue-visible"

    at /Users/.../node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17

    at Array.map (native)

    at Function.normalisePlugins (/Users/.../node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)

    at OptionManager.mergeOptions (/Users/.../node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)

    at OptionManager.init (/Users/.../node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)

    at File.initOptions (/Users/.../node_modules/babel-core/lib/transformation/file/index.js:212:65)

    at new File (/Users/.../node_modules/babel-core/lib/transformation/file/index.js:135:24)

    at Pipeline.transform (/Users/.../node_modules/babel-core/lib/transformation/pipeline.js:46:16)

    at transpile (/Users/.../node_modules/babel-loader/lib/index.js:46:20)

    at Object.module.exports (/Users/.../node_modules/babel-loader/lib/index.js:163:20)

    @ ./scripts/app/AppRunner.js 15:18-40
    @ ./scripts/app/.../...Entry.js

So there is a need the "transform-runtime" plugin must be installed for Babel, it's not correct - please write:
a) dependences and that is raws
b) give compiled file with map

**Comment by javisperez** [comment] 2017-05-30 22:12
Weird issue, I'm using this myself in many projects and have never seem that error. I'll have a look as soon as possible, thank you for letting me know! :)

**Comment by javisperez** [comment] 2017-07-01 16:27
Hey, I've given a look to this, but I'm unable to reproduce it. If you check the `package.json` file on line #38 (https://github.com/javisperez/vue-visible/blob/master/package.json) there's the dependency for the `transform-runtime` babel plugin. Maybe it didn't installed for you, can you please try doing `npm install` again? As I said, I'm unable to reproduce this.

**Comment by javisperez** [comment] 2018-06-19 02:18
Closing due lack of updates.

**Closed as completed by javisperez** 2018-06-19 02:18 UTC
